name: Sync SharePoint Excel

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch:     # Allows manual trigger

permissions:
  contents: write    # This line gives write permission to the workflow

jobs:
  download-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token for authentication

      - name: Ensure sync directory exists
        run: mkdir -p sync

      - name: Download Excel from SharePoint
        run: |
          curl -L -o sync/sharepoint_file.xlsx "https://trangantravel-my.sharepoint.com/:x:/g/personal/ly_opr_trangantravel_com_vn/EfdJWaw7LFFLk883msaMOXIByCzy5UdfWqPS5HQzBfLU7A?rtime=DEpsHGuX3Ug"

      - name: Commit and push if file changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add sync/sharepoint_file.xlsx
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update SharePoint Excel in sync folder"
            git push
          fi