name: Sync Google Sheet

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch:     # Allows manual trigger

permissions:
  contents: write    # This line gives write permission to the workflow

jobs:
  download-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}  # Use the Personal Access Token for authentication

      - name: Ensure sync directory exists
        run: mkdir -p sync

      - name: Download Google Sheet
        run: |
          curl -L -o sync/z.xls "https://docs.google.com/spreadsheets/d/1pLk43Z63h63fyDWJzLOBZlHGnPb7-ankZiV6f7YxprE/export?format=xlsx"

      - name: Commit and push if file changed
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add sync/z.xls
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update Google Sheet in sync folder"
            git push
          fi
